baseURL = "http://localhost:1313/"
languageCode = "es"
title = "FSS"
theme = "fss-theme"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6
    ordered = true
